tgun_enable: True
tgun_weapon: GunUSP

tgun_blacklist_173: true
tgun_scp_shotsneeded: 2

tgun_ammo: 18
tgun_damage: 1
tgun_sleepduration_min: 3.0
tgun_sleepduration_max: 5.0
#tgun_stun (Feature coming on the next SCP:SL update)
tgun_replacecomgun: true
tgun_accessdenied: <color=red>Access denied.</color>

tgun_warning_duration: 3
tgun_warning_text: <color=red>You fell asleep...</color>

tgun_pickedup_duration: 2
tgun_pickedup_text: <color=green><b>You picked up a tranquilizer gun!</b></color> \nEvery shot uses %ammo ammo, so count your bullets!

tgun_noammo_duration: 2
tgun_noammo_text: <color=red>You need %ammo ammo to fire your gun!</color>
